version: '3.8'

services:
  postgresql:
    container_name: container_postgresql
    image: postgres:17
    environment:
      POSTGRES_USER: mohammed
      POSTGRES_PASSWORD: mohammed
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5422:5432"
    # networks:
    #   - e-commerce-app_microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: container_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    # networks:
    #   - e-commerce-app_microservices-net  # Changement ici
    restart: unless-stopped


  # mongodb:
  #   image: mongo
  #   container_name: mongo_db
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - mongo:/data
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=mohammed
  #     - MONGO_INITDB_ROOT_PASSWORD=mohammed

#  mongo-express:
#    container_name: mongo-express
#    image: mongo-express
#    depends_on:
#      - mongodb
#    networks:
#      - e-commerce-app_microservices-net
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=mongo-dev
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
#      - ME_CONFIG_BASICAUTH_USERNAME=admin
#      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
#    ports:
#      - '8081:8081'



# networks:
#   e-commerce-app_microservices-net:
#     external: true  # Indiquer que le réseau est externe



volumes:
  postgres:
  pgadmin:
  # mongo:
